
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD ASSIGN BOOL COMMA DIVIDE DOUBLE DYNAMIC ELSE EQUALS FALSE FOR GQUAL ID IF INT LBRACE LDQMARK LESSTHAN LIST LPAREN LQUAL MAP MINUS MORETHAN NEW NOTEQUALS NUM NUMBER PLUS PRINT PUNTO RBRACE RDQMARK RPAREN SEMICOLON SET SQMARK STRING STRINGVAL TIMES TRUE VAR WHILEdeclarNum : NUM\n                | INT\n                | DOUBLE\n                | VAR\n                | DYNAMICresultado : declarNum STRINGVAL ASSIGN NUMBER SEMICOLONvalor : NUMBER\n             | IDresultado : valor PLUS valor SEMICOLONresultado : valor MINUS valor SEMICOLONresultado : valor TIMES valor SEMICOLONresultado : valor DIVIDE valor SEMICOLONstring : declarar STRINGVAL SEMICOLONdeclarar : VAR\n                | STRING\n                | DYNAMIC'
    
_lr_action_items = {'NUM':([0,],[2,]),'INT':([0,],[3,]),'DOUBLE':([0,],[4,]),'VAR':([0,],[5,]),'DYNAMIC':([0,],[6,]),'$end':([1,2,3,4,5,6,],[0,-1,-2,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declarNum':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declarNum","S'",1,None,None,None),
  ('declarNum -> NUM','declarNum',1,'p_VARIABLES_NUMEROS','Yacc.py',8),
  ('declarNum -> INT','declarNum',1,'p_VARIABLES_NUMEROS','Yacc.py',9),
  ('declarNum -> DOUBLE','declarNum',1,'p_VARIABLES_NUMEROS','Yacc.py',10),
  ('declarNum -> VAR','declarNum',1,'p_VARIABLES_NUMEROS','Yacc.py',11),
  ('declarNum -> DYNAMIC','declarNum',1,'p_VARIABLES_NUMEROS','Yacc.py',12),
  ('resultado -> declarNum STRINGVAL ASSIGN NUMBER SEMICOLON','resultado',5,'p_DECLARAR_NUMEROS','Yacc.py',15),
  ('valor -> NUMBER','valor',1,'p_VALOR','Yacc.py',18),
  ('valor -> ID','valor',1,'p_VALOR','Yacc.py',19),
  ('resultado -> valor PLUS valor SEMICOLON','resultado',4,'p_SUMA','Yacc.py',22),
  ('resultado -> valor MINUS valor SEMICOLON','resultado',4,'p_RESTA','Yacc.py',25),
  ('resultado -> valor TIMES valor SEMICOLON','resultado',4,'p_MULTIPLIACION','Yacc.py',28),
  ('resultado -> valor DIVIDE valor SEMICOLON','resultado',4,'p_DIVISION','Yacc.py',31),
  ('string -> declarar STRINGVAL SEMICOLON','string',3,'p_STRING','Yacc.py',36),
  ('declarar -> VAR','declarar',1,'p_STRING_DECLARAR','Yacc.py',39),
  ('declarar -> STRING','declarar',1,'p_STRING_DECLARAR','Yacc.py',40),
  ('declarar -> DYNAMIC','declarar',1,'p_STRING_DECLARAR','Yacc.py',41),
]
